{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "32e4cd29",
   "metadata": {},
   "outputs": [],
   "source": [
    "# import\n",
    "import gym\n",
    "import numpy as np\n",
    "from tensorflow.keras.models import Sequential, Model\n",
    "from tensorflow.keras.layers import Dense, Dropout, Input\n",
    "from tensorflow.keras.layers import Add, Multiply\n",
    "from tensorflow.keras.optimizers import Adam\n",
    "import tensorflow.keras.backend as K\n",
    "\n",
    "import tensorflow as tf\n",
    "import random\n",
    "from collections import deque"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "31a9bb44",
   "metadata": {},
   "outputs": [],
   "source": [
    "import tensorflow.compat.v1 as tf\n",
    "tf.disable_v2_behavior()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e644569f",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2022-12-09 11:41:50.104681: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA\n",
      "To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2022-12-09 11:41:50.134814: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3593190000 Hz\n",
      "2022-12-09 11:41:50.135511: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x3f54050 executing computations on platform Host. Devices:\n",
      "2022-12-09 11:41:50.135529: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version\n",
      "2022-12-09 11:41:50.135747: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3457, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_11383/1516610257.py\", line 150, in <module>\n",
      "    main()\n",
      "  File \"/tmp/ipykernel_11383/1516610257.py\", line 125, in main\n",
      "    K.set_session(sess)\n",
      "AttributeError: module 'tensorflow_core.keras.backend' has no attribute 'set_session'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2077, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'AttributeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/tensorflow/__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/tensorflow/__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 965, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3457, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_11383/1516610257.py\", line 150, in <module>\n",
      "    main()\n",
      "  File \"/tmp/ipykernel_11383/1516610257.py\", line 125, in main\n",
      "    K.set_session(sess)\n",
      "AttributeError: module 'tensorflow_core.keras.backend' has no attribute 'set_session'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2077, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'AttributeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3377, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3474, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2080, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1125, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2077, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/tensorflow/__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/tensorflow/__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 965, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3457, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_11383/1516610257.py\", line 150, in <module>\n",
      "    main()\n",
      "  File \"/tmp/ipykernel_11383/1516610257.py\", line 125, in main\n",
      "    K.set_session(sess)\n",
      "AttributeError: module 'tensorflow_core.keras.backend' has no attribute 'set_session'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2077, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'AttributeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3377, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3474, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2080, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1125, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2077, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2960, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3186, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3396, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2080, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1143, in structured_traceback\n",
      "    chained_exceptions_tb_offset)\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2077, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/tensorflow/__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/site-packages/tensorflow/__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"/home/soohyoen/anaconda3/envs/rein_study/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 965, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n"
     ]
    }
   ],
   "source": [
    "class ActorCritic:\n",
    "    def __init__(self, env, sess):\n",
    "        self.env = env\n",
    "        self.sess = sess\n",
    "        \n",
    "        self.learning_rate = 0.001\n",
    "        self.epsilon = 1.0\n",
    "        self.epsilon_decay = .995\n",
    "        self.gamma = .95\n",
    "        self.tau = .125\n",
    "        \n",
    "        self.memory = deque(maxlen=2000)\n",
    "        self.actor_state_input, self.actor_model = self.create_actor_model()\n",
    "        _, self.target_actor_model = self.create_actor_model()\n",
    "        \n",
    "        self.actor_critic_grad = tf.placeholder(tf.float32, [None, self.env.action_space,shape[0]])\n",
    "        \n",
    "        actor_model_weights = self.actor_model.trainable_weights\n",
    "        self.actor_grads = tf.gradients(self.actor_model.output, \n",
    "                                       actor_model_weights, -self.actor_critic_grad)\n",
    "        grads = zip(self.actor_grads, actor_model_weights)\n",
    "        self.optimize = tf.train.AdamOptimizer(self.learning_rate).apply_gradients(grads)\n",
    "        \n",
    "        self.acritic_state_input, self.critic_action_input, self.critic_model = self.create_critic_model()\n",
    "        _, _, self.target_critic_model = self.create_critic_model()\n",
    "        \n",
    "        self.critic_grads = tf.gradients(self.critic_model.output, self.critic_action_input)\n",
    "        \n",
    "        self.sess.run(tf.initialize_all_variables())\n",
    "        \n",
    "        def create_actor_model(self):\n",
    "            state_input = Input(shape = self.env.observation_space.shape)\n",
    "            h1 = Dense(24,activation='relu')(state_input)\n",
    "            h2 = Dense(48, activation = 'relu')(h1)\n",
    "            h3 = Dense(24, activation = 'relu')(h2)\n",
    "            output = Dense(self.env.action_space.shape[0], activation='relu')(h3)\n",
    "            \n",
    "            model = Model(input=state_input, output = output)\n",
    "            adam = Adam(lr=0.001)\n",
    "            model.compile(loss=\"mse\", optimizer=adam)\n",
    "            return state_input, model\n",
    "        \n",
    "        def create_critic_model(self):\n",
    "            state_input = Input(shape=self.env.observaion_space.shape)\n",
    "            state_h1 = Dense(24, activation='relu')(state_input)\n",
    "            state_h2 = Dense(48)(state_h1)\n",
    "            \n",
    "            action_input = Input(shape=self.env.action_space.shape)\n",
    "            action_h1 = Dense(48)(action_input)\n",
    "            \n",
    "            merged = Add()([state_h2, action_h1])\n",
    "            merged_h1 = Dense(24, activation = 'relu')(merged)\n",
    "            output = Dense(1, activation='relu')(merged_h1)\n",
    "            model = Model(input=[state_input, action_input], output=output)\n",
    "            \n",
    "            adam = Adam(lr=0.001)\n",
    "            model.compile(loss=\"mse\", optimizer=adam)\n",
    "            return state_input, action_input, model\n",
    "        \n",
    "        def remember(self,cur_state, action, reward, new_state,done):\n",
    "            self.memory.append([cur_state, action,reward, new_state,done])\n",
    "            \n",
    "        def _train_actor(self, samples):\n",
    "            for sample in samples:\n",
    "                cur_state, action,reward,new_state,_ = sample\n",
    "                predicted_action = self.actor_model.predict(cur_state)\n",
    "                grads = self.sess.run(self.critic_grads, feed_dict={\n",
    "                    self.critic_state_input : cur_state,\n",
    "                    self.critic_action_input : predicted_action\n",
    "                })[0]\n",
    "                \n",
    "                self.sess.run(self.optimize, feed_dict={\n",
    "                    self.actor_state_input : cur_state,\n",
    "                    self.actor_critic_grad: grads\n",
    "                })\n",
    "                \n",
    "        def _train_critic(self, samples):\n",
    "            for sample in samples:\n",
    "                cur_state,action, reward, new_state, done = smaple\n",
    "                if not done:\n",
    "                    target_action = self.targer_actor_model.predict(new_state)\n",
    "                    future_reward = self.target_critic_model.predict(\n",
    "                        [new_state, target_action])[0][0]\n",
    "                    reward += self.gamma * future_reward\n",
    "                self.critic_model.fit([cur_state, action], reward, verbose=0)\n",
    "         \n",
    "        def train(self):\n",
    "            batch_size = 32\n",
    "            if len(self.memory) < batch_size:\n",
    "                return\n",
    "            rewards = []\n",
    "            samples = random.sample(self.memorym, batch_size)\n",
    "            self._train_critic(samples)\n",
    "            self._train_actor(samples)\n",
    "            \n",
    "        \n",
    "        def _update_actor_target(self):\n",
    "            actor_model_weights = self.actor_model.get_weights()\n",
    "            actor_target_wegihts = self.target_critic_model.get_weights()\n",
    "            \n",
    "            for i in range(len(actor_target_weights)):\n",
    "                actor_target_weights[i] = actor_model_weights[i]\n",
    "            self.target_critic_model.set_weights(actor_target_weights)\n",
    "            \n",
    "        def _update_critic_target(self):\n",
    "            critic_model_weights = self.critic.model.get_weights()\n",
    "            critic_target_weights = self.critic_target_model.get_weights()\n",
    "            \n",
    "            for i in range(len(critic_target_weights)):\n",
    "                critic_target_weights[i] = ciritic_model_weights[i]\n",
    "            self.critic_target_model.set_weights(critic_target_weights)\n",
    "            \n",
    "        def update_target(self):\n",
    "            self._update_actor_target()\n",
    "            self._update_critic_target()\n",
    "            \n",
    "        def act(self,cur_state):\n",
    "            self.epsilon *= self.epsilon_decay\n",
    "            if np.random.random() < self.epsilon:\n",
    "                return self.env.action_space.smaple()\n",
    "            return self.actor_model.predict(cur_state)\n",
    "        \n",
    "def main():\n",
    "    sess = tf.Session()\n",
    "    K.set_session(sess)\n",
    "    env = gym.make(\"Pendulum-v0\")\n",
    "    actor_critic = ActorCritic(env,sess)\n",
    "    \n",
    "    num_trials = 10000\n",
    "    trial_len = 500\n",
    "    \n",
    "    cur_state = env.reset()\n",
    "    action = env.action_space.sample()\n",
    "    \n",
    "    while True:\n",
    "        env.render()\n",
    "        cur_state = cur_state.reshape((1,env.observation_space.shape[0]))\n",
    "        action = actor_critic.act(cur_state)\n",
    "        action = action.reshape((1,env,action_space.shape[0]))\n",
    "        \n",
    "        new_state, reward,done, _ = env.step(action)\n",
    "        new_state = new_state.reshape((1, env.observation_space.shape[0]))\n",
    "        \n",
    "        actor_critic.remember(cur_state, action, reward, new_state, done)\n",
    "        actor_critic.train()\n",
    "        \n",
    "        cur_state = new_state\n",
    "        \n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a0f649e3",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "rein_study",
   "language": "python",
   "name": "rein_study"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
